### ISSUE TITLE
update website copy 

### ISSUE THREAD

**Issue by levlite** [vulcanize/vulcanize.io#3]
please update the website copy on vulcanize.io to include the following copy: 

Specializing in mechanism design with an emphasis on proof-of-stake systems, Vulcanize advises its clients on an assortment of topics related to the development and deployment of blockchain-based systems. Vulcanize has received grants from Protocol Labs, Interchain Foundation, Uniswap, MolochDAO, and from the Ethereum Foundation for its contribution to EIP-1559.

**Comment by AFDudley** [comment]
Resolved in https://github.com/vulcanize/vulcanize.io/commit/31836bd7da14a9255ef3eda7b1f14e0a17c932c9
